openapi: 3.0.0
info:
  description: WASAPhoto app backend REST API
  title: WASAPhoto API
  version: 1.0.0
components:
  schemas:
    User:
      title: User
      description: "This object represent a user in WASAPhoto"
      type: object
      properties:
        username:
          description: User's username
          type: string
          example: user
        numFollowers:
          description: User's number of followers
          type: integer
          example: 100
          readOnly: true
        numFollowing:
          description: User's number of following profiles
          type: integer
          example: 200
          readOnly: true
        numPhotos:
          description: User's number of photos uploaded
          type: integer
          example: 10
          readOnly: true
    Photo:
      title: Photo
      description: "This object represent a photo in WASAPhoto"
      type: object
      properties:
        numLikes:
          description: Photo's number of like
          type: integer
          example: 30
          readOnly: true
        numComments:
          description: Photo's number of comments
          type: integer
          example: 20
          readOnly: true
        date&time:
          description: Photo's date of uploading
          type: string
          format: date-time
          example: "2023-11-06T17:32:28Z"
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'Ë†.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                    type: string
                    example: "abcdef012345"
  